version: '3.9'

services:
  jenkins:
    build: .
    ports:
      - '8080:8080'
      - '50000:50000'
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins_home:/var/jenkins_home
  docker:
    image: docker:dind
    privileged: true
    ports:
      - '2376:2376'
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins_home:/var/jenkins_home
    command: --storage-driver=overlay2

volumes:
  jenkins_home:
  jenkins-docker-certs:
